baseURL = 'yukigunigames.com/'
languageCode = 'en-us'
title = 'Yuki Guni Games'
theme = 'hello-friend-ng'
paginate = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A video game studio"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Home of Yuki Guni Games"
  keywords = "homepage"
  images = [""]

#[taxonomies]
    #category = "blog"
    #tag      = "tags"
    #series   = "series"

[languages]
  [languages.en]
    title = "Yuki Guni Games"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A video game studio"

    [languages.en.params.logo]
      logoText = "雪国"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  #[[menu.main]]
    #identifier = "blog"
    #name       = "Blog"
    #url        = "/posts"
	
  #[[menu.main]]
    #identifier = "faq"
    #name       = "FAQ"
    #url        = "/faq"