baseURL = 'yukigunigames.com/'
languageCode = 'en-us'
title = 'Yuki Guni Games'
theme = 'hello-friend-ng'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Title for home
  #homeTitle = "Yuki Hello"

  # Subtitle for home
  homeSubtitle = "Porting. Co-dev. Video games."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  #enableThemeToggle = true
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Porting. Co-dev. Video games."
  keywords = "homepage"
  images = [""]
  
  plausibleDataDomain = 'yukigunigames.com'
  plausibleScriptSource = 'https://plausible.io/js/script.js'
  
  [params.logo]
    logoCursorDisabled = true
    logoCursorPathname = false
    #logoMark = ">"
    logoMark = " "

# These are only here to prevent Hugo issues
[taxonomies]
    category = "categories"
    tag      = "tags"
    #series   = "series"

[languages]
  [languages.en]
    title = "Yuki Guni Games"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A video game studio"

    [languages.en.params.logo]
      logoText = "雪国"
      #logoText = "$ cd /雪国/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
	
[[params.social]]
  name = "email"
  url = "mailto:info@yukigunigames.com"
	
[[params.social]]
  name = "bluesky"
  url = "https://bsky.app/profile/yukiguni.games"
  
[[params.social]]
  name = "mastodon"
  url = "https://mastodon.gamedev.place/@yukigunigames"
  
#[[params.social]]
  #name = "instagram"
  #url = "https://www.instagram.com/yukigunigames/"